### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by robinheidrich** [Tach-Yon/Tap-Tap-Adventure#26]
Hello. It seems as if some files are not present in the repo.
If I now want to start my server, the following error appears:
node server/js/main.js

module.js:340
    throw err;
    ^
Error: Cannot find module './../../../utils/variations'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/server/js/game/entity/character/player/player.js:20:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Also missing some files in the client (js).

**Comment by Tach-Yon** [comment]
Nothing should be missing in the client-side.

**Comment by robinheidrich** [comment]
Now i'm getting:
module.js:340
    throw err;
    ^
Error: Cannot find module '../quests/introduction'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/server/js/game/handlers/questhandler.js:2:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by Tach-Yon** [comment]
@robinheidrich Those are simple path errors, you can figure them out without my help..

**Comment by robinheidrich** [comment]
Looks like you forgot another file in server-folder:
[Mon Feb 06 2017 14:50:46 GMT+0100 (CET)] ERROR uncaughtException: ReferenceError: Variations is not defined
used in:
server/js/game/entity/character/player/player.js:80
