### ISSUE TITLE
ReferenceError: achievemntId is not defined

### ISSUE THREAD

**Issue by wini3d** [Tach-Yon/Tap-Tap-Adventure#31]
@Tach-Yon While roaming around and talking with NPCs with achievements, this is always being thrown by server. I see the achievement data file is there, but still throwing this error.

**Comment by Tach-Yon** [comment]
Post full error please?

**Comment by wini3d** [comment]
Hi, yes sorry here it is:

```
ERROR uncaughtException: ReferenceError: achievemntId is not defined
    at Class.foundAchievement (C:\nodejs\taptap\server\js\game\entity\character\player\player.js:366:26)
    at Class.handleTalkToNPC (C:\nodejs\taptap\server\js\game\handlers\packethandler.js:444:33)
    at Class.listenCallback (C:\nodejs\taptap\server\js\game\handlers\packethandler.js:167:26)
    at Socket.<anonymous> (C:\nodejs\taptap\server\js\game\network\ws.js:310:26)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at C:\nodejs\taptap\node_modules\socket.io\lib\socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Tach-Yon** [comment]
@wini3d Oh my, stupid typo, let me do a quick fix

**Comment by Tach-Yon** [comment]
Should be fixed now.

**Comment by wini3d** [comment]
Awesome thanks! :smile:
