### ISSUE TITLE
TypeError: Cannot read property 'shift' of undefined

### ISSUE THREAD

**Issue by tgraupne** [Tach-Yon/Tap-Tap-Adventure#40]
Hi,

I just tried to run this application inside a debian docker container and I get the following error message when I try to log in.

`root@1e823b293567:/usr/local/Tap-Tap-Adventure# node server/js/main.js
[Mon Oct 09 2017 22:24:39 GMT+0000 (UTC)] NOTICE Initializing Tap Tap Adventure game engine...
[Mon Oct 09 2017 22:24:40 GMT+0000 (UTC)] NOTICE Server is now listening on: 1800
[Mon Oct 09 2017 22:24:40 GMT+0000 (UTC)] INFO Successfully established connection to the MySQL database!
[Mon Oct 09 2017 22:24:40 GMT+0000 (UTC)] NOTICE Finished creating 1 world!
[Mon Oct 09 2017 22:24:40 GMT+0000 (UTC)] INFO ************ World 1 ***********
[Mon Oct 09 2017 22:24:40 GMT+0000 (UTC)] INFO Loaded 0 PVP areas.
[Mon Oct 09 2017 22:24:40 GMT+0000 (UTC)] INFO Loaded 72 music areas.
[Mon Oct 09 2017 22:24:40 GMT+0000 (UTC)] INFO ********************************
[Mon Oct 09 2017 22:24:40 GMT+0000 (UTC)] INFO Finished loading 130 mobs.
[Mon Oct 09 2017 22:24:40 GMT+0000 (UTC)] INFO Finished loading 45 NPCs.
[Mon Oct 09 2017 22:24:40 GMT+0000 (UTC)] INFO Finished loading 257 items.
[Mon Oct 09 2017 22:24:40 GMT+0000 (UTC)] INFO Finished loading 3 skills.
[Mon Oct 09 2017 22:24:40 GMT+0000 (UTC)] INFO [Map] Successfully loaded the collision grid!
[Mon Oct 09 2017 22:24:40 GMT+0000 (UTC)] INFO Spawned 924 entities!
[Mon Oct 09 2017 22:24:59 GMT+0000 (UTC)] NOTICE Received connection from: 172.17.0.1
[Mon Oct 09 2017 22:24:59 GMT+0000 (UTC)] INFO Username not available.
[Mon Oct 09 2017 22:24:59 GMT+0000 (UTC)] NOTICE Closed socket: 172.17.0.1
[Mon Oct 09 2017 22:25:09 GMT+0000 (UTC)] NOTICE Received connection from: 172.17.0.1
[Mon Oct 09 2017 22:25:09 GMT+0000 (UTC)] INFO Username not available.
[Mon Oct 09 2017 22:25:09 GMT+0000 (UTC)] NOTICE Closed socket: 172.17.0.1
[Mon Oct 09 2017 22:25:19 GMT+0000 (UTC)] NOTICE Received connection from: 172.17.0.1
[Mon Oct 09 2017 22:25:20 GMT+0000 (UTC)] ERROR MySQL database disconnected.
[Mon Oct 09 2017 22:25:20 GMT+0000 (UTC)] ERROR MySQL database disconnected.
[Mon Oct 09 2017 22:25:20 GMT+0000 (UTC)] INFO Successfully established connection to the MySQL database!
/usr/local/Tap-Tap-Adventure/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Cannot read property 'shift' of undefined
    at Query._callback (/usr/local/Tap-Tap-Adventure/server/js/database/loader.js:17:28)
    at Query.Sequence.end (/usr/local/Tap-Tap-Adventure/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query.ErrorPacket (/usr/local/Tap-Tap-Adventure/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/usr/local/Tap-Tap-Adventure/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/usr/local/Tap-Tap-Adventure/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/usr/local/Tap-Tap-Adventure/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/usr/local/Tap-Tap-Adventure/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)`

I followed your installation guide briefly. But in addition to that I had to also install mysql, create a database and update the file server/config.json with the appropriate configuration.

I would be a blast to get some help on this.

**Comment by Tach-Yon** [comment]
Depending on the MySQL you have set up, either you are missing the database or the user has restricted access and cannot generate one. In either case, connect to the database and dump the SQL file located in the `tools` folder. Start the server again and that should do it.

**Comment by tgraupne** [comment]
I’ve created just 1 database called `taptap` and I think the user root should be able to write to this database, am I right?

Is there a special database setup necessary?

**Comment by Tach-Yon** [comment]
I’ve also stated there is a SQL file in the tools folder. Just run it in the database so it creates all the tables.

**Comment by tgraupne** [comment]
The import of the sql file worked.
But now I get 'Email address is not available' error messages during login :-D

What does that even mean? Is your app actively trying to validate email addresses?

**Comment by Tach-Yon** [comment]
Might be because it is still connected to the main game API for validating user accounts.
