### ISSUE TITLE
Erreur MySQL/MariaDB

### ISSUE THREAD

**Issue by Sigri44** [Tach-Yon/Tap-Tap-Adventure#62]
When i launch the server (database.sql as import at mysql/mariadb) : 
```
[Mon Jan 22 2018 15:25:17 GMT+0100 (CET)] NOTICE Initializing Tap Tap Adventure game engine...
[Mon Jan 22 2018 15:25:18 GMT+0100 (CET)] INFO false
[Mon Jan 22 2018 15:25:18 GMT+0100 (CET)] NOTICE Server is now listening on: 1800
[Mon Jan 22 2018 15:25:18 GMT+0100 (CET)] INFO [MySQL] No database found...
[Mon Jan 22 2018 15:25:18 GMT+0100 (CET)] INFO [MySQL] Creating database....
/root/Tap-Tap-Adventure/server/js/database/mysql.js:171
                throw error;
                ^

Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MariaDB client
    at Handshake.Sequence._packetToError (/root/Tap-Tap-Adventure/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/root/Tap-Tap-Adventure/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)
    at Protocol._parsePacket (/root/Tap-Tap-Adventure/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/root/Tap-Tap-Adventure/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/root/Tap-Tap-Adventure/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/Tap-Tap-Adventure/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
    --------------------
    at Protocol._enqueue (/root/Tap-Tap-Adventure/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/root/Tap-Tap-Adventure/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at Connection.connect (/root/Tap-Tap-Adventure/node_modules/mysql/lib/Connection.js:130:18)
    at Connection._implyConnect (/root/Tap-Tap-Adventure/node_modules/mysql/lib/Connection.js:461:10)
    at Connection.query (/root/Tap-Tap-Adventure/node_modules/mysql/lib/Connection.js:206:8)
    at Class.loadDatabases (/root/Tap-Tap-Adventure/server/js/database/mysql.js:169:25)
    at Handshake._callback (/root/Tap-Tap-Adventure/server/js/database/mysql.js:62:22)
    at Handshake.Sequence.end (/root/Tap-Tap-Adventure/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Handshake.ErrorPacket (/root/Tap-Tap-Adventure/node_modules/mysql/lib/protocol/sequences/Handshake.js:132:8)
    at Protocol._parsePacket (/root/Tap-Tap-Adventure/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/root/Tap-Tap-Adventure/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/root/Tap-Tap-Adventure/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/Tap-Tap-Adventure/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
```

**Comment by Sigri44** [comment]
Add GRANT ALL PRIVILEGES to taptap database with your user of config.js
