### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by TorchwoodPL** [Tach-Yon/Tap-Tap-Adventure#72]
Howdy,

I have problem, and I do not know why, I run server and I get:

> # node /var/www/subdomains/mmo/server/js/main.js
> [Sun Mar 25 2018 12:17:11 GMT+0200 (CEST)] NOTICE Initializing Tap Tap Adventure game engine...
> [Sun Mar 25 2018 12:17:11 GMT+0200 (CEST)] NOTICE Server is now listening on: 1800
> [Sun Mar 25 2018 12:17:11 GMT+0200 (CEST)] INFO Successfully established connection to the MySQL database!
> [Sun Mar 25 2018 12:17:11 GMT+0200 (CEST)] INFO Finished loading 131 mobs.
> [Sun Mar 25 2018 12:17:11 GMT+0200 (CEST)] INFO Loaded 6 mob plugins.
> [Sun Mar 25 2018 12:17:11 GMT+0200 (CEST)] INFO Finished loading 45 NPCs.
> [Sun Mar 25 2018 12:17:11 GMT+0200 (CEST)] INFO Finished loading 258 items.
> [Sun Mar 25 2018 12:17:11 GMT+0200 (CEST)] INFO Loaded 1 item plugins.
> [Sun Mar 25 2018 12:17:11 GMT+0200 (CEST)] INFO Finished loading 3 skills.
> [Sun Mar 25 2018 12:17:11 GMT+0200 (CEST)] INFO Finished loading 1 shops.
> [Sun Mar 25 2018 12:17:11 GMT+0200 (CEST)] INFO ************ World 1 ***********
> [Sun Mar 25 2018 12:17:11 GMT+0200 (CEST)] INFO Loaded 1 PVP areas.
> [Sun Mar 25 2018 12:17:11 GMT+0200 (CEST)] INFO Loaded 74 music areas.
> [Sun Mar 25 2018 12:17:11 GMT+0200 (CEST)] INFO Loaded 9 chest areas.
> [Sun Mar 25 2018 12:17:11 GMT+0200 (CEST)] INFO Spawned 10 static chests
> [Sun Mar 25 2018 12:17:12 GMT+0200 (CEST)] INFO Spawned 904 entities!
> [Sun Mar 25 2018 12:17:12 GMT+0200 (CEST)] INFO The map has been successfully loaded!
> [Sun Mar 25 2018 12:17:12 GMT+0200 (CEST)] INFO Guild controller initialized with 1 guilds.
> [Sun Mar 25 2018 12:17:12 GMT+0200 (CEST)] INFO ********************************
> [Sun Mar 25 2018 12:17:12 GMT+0200 (CEST)] NOTICE Finished creating 1 world!
> [Sun Mar 25 2018 12:17:12 GMT+0200 (CEST)] NOTICE Connect locally via http://77.55.208.240:1800

But on browser I only get:
Cannot GET /

Can anybody tell my what it is like that?

**Comment by TorchwoodPL** [comment]
When I redownload everything I do not get above error by when I try to create new char I get:

> [Sun Mar 25 2018 12:32:07 GMT+0200 (CEST)] INFO No player data found. Creating new player data for: Boberski
> [Sun Mar 25 2018 12:32:07 GMT+0200 (CEST)] ERROR { Error: ER_BAD_FIELD_ERROR: Unknown column 'lastWarp' in 'field list'
>     at Query.Sequence._packetToError (/var/www/subdomains/mmo/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
>     at Query.ErrorPacket (/var/www/subdomains/mmo/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
>     at Protocol._parsePacket (/var/www/subdomains/mmo/node_modules/mysql/lib/protocol/Protocol.js:279:23)
>     at Parser.write (/var/www/subdomains/mmo/node_modules/mysql/lib/protocol/Parser.js:76:12)
>     at Protocol.write (/var/www/subdomains/mmo/node_modules/mysql/lib/protocol/Protocol.js:39:16)
>     at Socket.<anonymous> (/var/www/subdomains/mmo/node_modules/mysql/lib/Connection.js:103:28)
>     at emitOne (events.js:116:13)
>     at Socket.emit (events.js:211:7)
>     at addChunk (_stream_readable.js:263:12)
>     at readableAddChunk (_stream_readable.js:250:11)
>     at Socket.Readable.push (_stream_readable.js:208:10)
>     at TCP.onread (net.js:607:20)
>     --------------------
>     at Protocol._enqueue (/var/www/subdomains/mmo/node_modules/mysql/lib/protocol/Protocol.js:145:48)
>     at Connection.query (/var/www/subdomains/mmo/node_modules/mysql/lib/Connection.js:208:25)
>     at Class.save (/var/www/subdomains/mmo/server/js/database/creator.js:146:31)
>     at Query._callback (/var/www/subdomains/mmo/server/js/database/mysql.js:143:30)
>     at Query.Sequence.end (/var/www/subdomains/mmo/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
>     at Query._handleFinalResultPacket (/var/www/subdomains/mmo/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
>     at Query.EofPacket (/var/www/subdomains/mmo/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
>     at Protocol._parsePacket (/var/www/subdomains/mmo/node_modules/mysql/lib/protocol/Protocol.js:279:23)
>     at Parser.write (/var/www/subdomains/mmo/node_modules/mysql/lib/protocol/Parser.js:76:12)
>     at Protocol.write (/var/www/subdomains/mmo/node_modules/mysql/lib/protocol/Protocol.js:39:16)
>     at Socket.<anonymous> (/var/www/subdomains/mmo/node_modules/mysql/lib/Connection.js:103:28)
>     at emitOne (events.js:116:13)
>     at Socket.emit (events.js:211:7)
>     at addChunk (_stream_readable.js:263:12)
>     at readableAddChunk (_stream_readable.js:250:11)
>     at Socket.Readable.push (_stream_readable.js:208:10)
>   code: 'ER_BAD_FIELD_ERROR',
>   errno: 1054,
>   sqlMessage: 'Unknown column \'lastWarp\' in \'field list\'',
>   sqlState: '42S22',
>   index: 0,
>   sql: 'INSERT INTO `player_data` SET `username` = \'Boberski\', `email` = \'null\', `x` = -1, `y` = -1, `experience` = 0, `kind` = 0, `rights` = 0, `poisoned` = 0, `hitPoints` = -1, `mana` = 20, `pvpKills` = 0, `pvpDeaths` = 0, `rank` = 0, `ban` = 0, `mute` = 0, `membership` = 0, `lastLogin` = 0, `guild` = \'[object Object]\', `lastWarp` = 0' }

**Comment by TorchwoodPL** [comment]
And now back to 404 error prom first post...

**Comment by TorchwoodPL** [comment]
Also there is no problem if you play as a quest.... Dummy fix od 404 error is to remove directory with game and recreate all...

**Comment by TorchwoodPL** [comment]
Also the funny thing is that yesterday all was working fine today I get this error:
https://github.com/Tach-Yon/Tap-Tap-Adventure/issues/65

And also all from above... and I do not know why because I was not doin anything...

**Comment by TorchwoodPL** [comment]
One more thing alter I try to register new account and get "Unknown column 'lastWarp' in 'field list'" error, if I restart server and try to access site I get "Cannot GET /" error. Then When I remove everything and redownload engine and setup database, I gain access and get rid of 404 error. But db is all new so I do not have my character :P

**Comment by TorchwoodPL** [comment]
I fix database no when I try to log in on my character I get:

> [Sun Mar 25 2018 18:28:09 GMT+0200 (CEST)] NOTICE Connect locally via http://77.55.208.240:1800
> [Sun Mar 25 2018 18:28:23 GMT+0200 (CEST)] NOTICE Received connection from: 217.113.226.156
> [Sun Mar 25 2018 18:28:23 GMT+0200 (CEST)] INFO Could not decipher API message
> [Sun Mar 25 2018 18:28:23 GMT+0200 (CEST)] INFO API response is malformed!
> [Sun Mar 25 2018 18:28:23 GMT+0200 (CEST)] NOTICE Closed socket: 217.113.226.156
> [Sun Mar 25 2018 18:28:23 GMT+0200 (CEST)] INFO Initiating login for: Boberski

And next time I get that my character is logged so I cannot log in more...
