### ISSUE TITLE
TypeError: cache.get is not a function

### ISSUE THREAD

**Issue by jasondaigo** [Tach-Yon/Tap-Tap-Adventure#80]
after getting an error after i tried to deploy this i tested offline mode and got the same error as shown below; what could this be? wont be my only question i guess as there are so little ressources how to host this.

node server/js/main.js
[Tue May 01 2018 18:48:05 GMT+0200 (CEST)] NOTICE Initializing Tap Tap Adventure game engine...
[Tue May 01 2018 18:48:05 GMT+0200 (CEST)] INFO Loaded 1 PVP areas.
[Tue May 01 2018 18:48:05 GMT+0200 (CEST)] INFO Loaded 74 music areas.
[Tue May 01 2018 18:48:05 GMT+0200 (CEST)] INFO Loaded 9 chest areas.
internal/modules/cjs/loader.js:59
    const result = cache.get(filename);
                         ^

TypeError: cache.get is not a function
    at stat (internal/modules/cjs/loader.js:59:26)
    at Function.Module._findPath (internal/modules/cjs/loader.js:214:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:546:25)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/jason/Tap-Tap-Adventure/server/js/game/entity/character/mob/mob.js:1:79)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/jason/Tap-Tap-Adventure/server/js/game/world.js:11:11)
    at Module._compile (internal/modules/cjs/loader.js:654:30)

**Comment by Tach-Yon** [comment]
Wrong NPM/NodeJS version, make sure you're at >= 8.9.4

**Comment by mrrapha-fullstack** [comment]
I'm having the same issue and my Node version is v10.8.0
