### ISSUE TITLE
Cache error in cjs/loader.js

### ISSUE THREAD

**Issue by giviz** [Tach-Yon/Tap-Tap-Adventure#88]
Hi !

I'm looking to test that game and I'm trying to get it running but have that error : 

```

giviz@localhost:/home/t.test/Tap-Tap-Adventure$ node server/js/main.js
[Sat Jul 07 2018 01:51:25 GMT-0400 (EDT)] NOTICE Initializing Tap Tap Adventure game engine...
[Sat Jul 07 2018 01:51:25 GMT-0400 (EDT)] INFO Loaded 1 PVP areas.
[Sat Jul 07 2018 01:51:25 GMT-0400 (EDT)] INFO Loaded 74 music areas.
[Sat Jul 07 2018 01:51:25 GMT-0400 (EDT)] INFO Loaded 9 chest areas.
internal/modules/cjs/loader.js:59
    const result = cache.get(filename);
                         ^

TypeError: cache.get is not a function
    at stat (internal/modules/cjs/loader.js:59:26)
    at Function.Module._findPath (internal/modules/cjs/loader.js:214:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:546:25)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/t.test/Tap-Tap-Adventure/server/js/game/entity/character/mob/mob.js:1:79)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/t.test/Tap-Tap-Adventure/server/js/game/world.js:11:11)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
```

```
giviz@localhost:/home/t.test/Tap-Tap-Adventure$ node -v
v9.11.2

```

Any idea what my cause that and how I can fix it ?

Thanks !

**Comment by Tach-Yon** [comment]
My guess is either something wrong with your NodeJS version or your permissions for the machine you’re running this on are whack.

**Comment by giviz** [comment]
I've updated node to 10.6.0 and set the whole directory permissions to 777.

Still the same error :(

Any other idea on what might cause that ?

I'm trying to run it on a debian 9.4, on what platform have you the last commit running fine ?

Thanks !

**Comment by Tach-Yon** [comment]
Running perfectly fine on Ubuntu 16.04, Mac OS X and Windows 10, using NodeJS 8.9.4 and NPM 6.0.0
